### PR TITLE
Update keycloak to run it using HTTPS

### PR DESCRIPTION
**Pull request by cmoulliard**
- Add maven plugins to generate Keys
- Run the bash script to create the secret and import the keystore & password
- Add a SSL profile
- Use a docker-entrypoint.Sh to launch keycloak using SSL

### CODE REVIEW

**Comment by cmoulliard** [comment]
Tested sucessfully with Openshift Origin & Apiman/Apiman-Gateway

**Comment by jimmidyson** [comment]
ok to test

**Comment by cmoulliard** [comment]
FYI : Tested sucessfully with Openshift Origin & Apiman/Apiman-Gateway

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
