### PR TITLE
lets migrate to the new gogs image name's folder structure and new im…

### PR DESCRIPTION
**Pull request by jstrachan**
…age tag

### CODE REVIEW

**Comment by jstrachan** [comment]
@jimmidyson does this look right to you? So from a PVC perspective we'd just need one PV right? Also it looks like there's no chmod / chgrp in this branch
https://github.com/fabric8io/docker-gogs/blob/0.9.71/start.sh#L22

when I try use it locally on minikube I get permission issues as the PV is owned by root/root so gogs barfs on startup:
```
2016/09/01 15:35:27 [.../gogs/models/repo.go:121 NewRepoContext()] [E] Fail to set git user.name(exit status 255): error: could not lock config file /app/gogs/data/.gitconfig: Permission denied
```

**Comment by jimmidyson** [comment]
> So from a PVC perspective we'd just need one PV right?

Yes.

> it looks like there's no chmod / chgrp in this branch

Why should there be? If `the PV is owned by root/root` there's nothing another user can do to chown it to itself... Setting up the PV permissions would be a requirement of the admin I guess. What type of PV are you using?

**Comment by jstrachan** [comment]
@jimmidyson so since gogs runs using the gogs user, it seems we get file permission issues when using the PV. Using HostPort PVs via `gofabric8 volumes`

The same PVC / PV configurations are working great for jenkins - as it runs as root ;)

Given the PV is owned by root/root how can the folders be used by non root containers?

**Comment by jstrachan** [comment]
BTW the jenkins PVC / PV change is here: https://github.com/fabric8io/fabric8-devops/pull/546

**Comment by jstrachan** [comment]
@jimmidyson so after a, say, HostPath PV is created, do we need to try figure out the effective user id of the container thats gonna user them, then do the chmod on the host machine so that the PV can be used?

**Comment by jimmidyson** [comment]
HostPath PVs are useless really & should be avoided. You have to set permissions for the effective UID as part of PV provisioning, impossible on OpenShift tbh.

Jenkins also should not run as root of course.

From http://kubernetes.io/docs/user-guide/volumes/#hostpathhttp://kubernetes.io/docs/user-guide/volumes/#hostpath (especially last point):

> Watch out when using this type of volume, because:
> * pods with identical configuration (such as created from a podTemplate) may behave differently on different nodes due to different files on the nodes
> * when Kubernetes adds resource-aware scheduling, as is planned, it will not be able to account for resources used by a hostPath
> * the directories created on the underlying hosts are only writable by root, you either need to run your process as root in a priveleged container or modify the file permissions on the host to be able to write to a hostPath volume

**Comment by jimmidyson** [comment]
For Jenkins you should probably talk to @bparees about how they've done PV provisioning for that on OpenShift so we can copy.

**Comment by jstrachan** [comment]
so we need to find a PV implementation we can use on minikube/minishift if hostPaths don't work

**Comment by jstrachan** [comment]
is emptyDir any better or would that offer the same permission issues? 
http://kubernetes.io/docs/user-guide/volumes/#emptydir

I guess deleting a pod using `kubectl delete pod foo` would result in the loss of persistence in minikube/minishift due to a different pod id starting next time right?

**Comment by jimmidyson** [comment]
Yeah. We need to discuss with OpenShift bods to understand if we can create PVs automatically & what they recommend.

emptyDir is only for transient data, won't help in this case.

**Comment by jstrachan** [comment]
for OpenShift Dedicated and Online its less of an issue; we can reuse the PVs created automatically there. No idea if we'll have similar permission issues yet mind you - seems [PVs don't bind properly yet on Dedicated](https://bugzilla.redhat.com/show_bug.cgi?id=1372458)

So this is mostly right now an issue for minikube/minishift. I guess we could experiment running an NFS server in minikube/minishift and trying NFS volumes? Not sure thats got anything special for permission handling either though

**Comment by jimmidyson** [comment]
Perhaps containerized gluster might be able to help or ceph but really not sure & need guidance.

NFS will have probably the same permissions issue.

**Comment by jstrachan** [comment]
we might have to work around this with gofabric8; for mini* create the hostPaths and do the chmod / chown based on annotations or something?

**Comment by jimmidyson** [comment]
For mini* we can always create hostPath volumes with 777 :)

**Comment by jstrachan** [comment]
@jimmidyson thats just what I was thinking :) at least we'll have something that kinda works then :)

**Comment by jstrachan** [comment]
@jimmidyson BTW when do you think we should switch over to the `v0.9.7x` flavour of the gogs docker image?

**Comment by jstrachan** [comment]
@jimmidyson almost have a workaround in gofabric8 for mini* by using `minishift ssh` or `minikube ssh` to then create the hostPath with an open permission scheme for now. Just need to polish the detection code to know whether we need to use `minikube | minishift | vagrant` as the main app to do the ssh...

**Comment by rawlingsj** [comment]
Nice!  There's also another one: `docker-machine ssh openshift` if folks have used `oc cluster up`

**Comment by jstrachan** [comment]
@rawlingsj ah great - wonder how we'll know that `docker-machine ssh openshift` should be required?

**Comment by rawlingsj** [comment]
Maybe the name of the VM, but I cant seem to get it to start now!  Will keep trying.

**Comment by rawlingsj** [comment]
Well I'm not sure how you can tell actually, the node name is just an IP address so lets not worry about oc cluster up for now

**Comment by jimmidyson** [comment]
So Kubernetes 1.4 has the concept of dynamic PV provisioning, which includes host path so we should test with that. We'd have to see how OpenShift handles that as well.

**Comment by jstrachan** [comment]
on the `vagrant v minishift v minikube` v `docker-machine ssh openshift` thingy, lets see if we can make minikube + minishift easier to grok (e.g. can we annotate the node with the installer?). We can leave the others out as a magic CLI argument ;)

**Comment by bparees** [comment]
we don't provision PVs w/ permissions, we set permissions on the volume when we assign it to a pod.  The permissions are set to match the uid/groupid of the container:
https://docs.openshift.org/latest/install_config/persistent_storage/pod_security_context.html#supplemental-groups
https://docs.openshift.org/latest/install_config/persistent_storage/pod_security_context.html#fsgroup

For our jenkins template we offer two:
1) one that uses ephemeral storage, k8s gives us an emptydir volume which we have write access to
2) one that uses a PV via a PVC which gets the right permissions assigned when it is mounted to the pod

that's about the end of my storage knowledge, so if you want more details you'll need to check with steve watt or brad childs who work on the storage team.

**Comment by jstrachan** [comment]
thanks for the heads up @bparees 

I tried using the security context on the pod via uid/gid, but the HostPath that got created was owned by root/root. 
```yaml
    spec:
      volumes:
      - name: gogs-data
        persistentVolumeClaim:
          claimName: gogs-data
      securityContext:
        supplementalGroups:
        - 1000
        fsGroup: 1000
      containers:
...
```

@bparees I wonder if anyone's got PVs working for Jenkins with openshift with HostPath? It could be the supplemental group / fsGroup stuff only works for NFS/gluster but not HostPath PVs?

**Comment by jstrachan** [comment]
@jimmidyson BTW the `v0.9.71` version fails on OpenShift for me; thats a known issue right?
```
whoami: unknown uid 1000030000
mkdir: can't create directory '/app/gogs/data/git': File exists
2016/09/02 11:05:25 Creating admin user:  true
2016/09/02 11:05:25 [...s/setting/setting.go:484 NewContext()] [E] Expect user 'git' but current user is:
```

**Comment by bparees** [comment]
> @bparees I wonder if anyone's got PVs working for Jenkins with openshift with HostPath? It could be the supplemental group / fsGroup stuff only works for NFS/gluster but not HostPath PVs? 

yes i'm pretty sure the fsgroup stuff is only for the shared volume plugins.  for hostpath you need two things:

1) the host dir needs to be 777 (or something pretty permissive) since your container is running as a random uid
2) the selinux labels on the host dir need to be set correctly to whatever docker likes.  you can start by disabling selinux to see if that is your problem.

i haven't tried running w/ a hostpath volume myself, though.

As for the unknown uid, you need to use nss wrapper to setup a proper mapping between the random uid assigned to your container, and whatever user you want to be.  See the "support arbitrary uids" section of this doc, which covers how to set this up properly:
https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines

you can also look at our jenkins image which handles it:
https://github.com/openshift/jenkins/tree/master/1
https://github.com/openshift/jenkins/blob/master/1/contrib/jenkins/jenkins-common.sh#L13-L28

**Comment by jimmidyson** [comment]
@bparees Thanks for that info - very helpful. It means we have to migrate to the much bulkier `centos:7` image, but that's not too bad I guess. nss wrapper seems to be working great. Thanks again!

**Comment by bparees** [comment]
cool!

**Comment by jstrachan** [comment]
@jimmidyson the new docker image looks good on openshift now thanks [merge]

**Pull request merged**
