### PR TITLE
migrate gogs and gerrit

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by jstrachan** [comment]
[merge]

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
[merge]

**Comment by jstrachan** [comment]
ok to test

**Comment by rawlingsj** [comment]
retest this please

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
retest this please

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
[merge]

**Comment by jstrachan** [comment]
retest this please

**Comment by jstrachan** [comment]
[merge]

**Pull request merged**
