### PR TITLE
remove external loadbalancer from kubernetes services now that we use ingress

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
[merge]

**Comment by rawlingsj** [comment]
ok to test

**Comment by jstrachan** [comment]
ok to test

**Comment by rawlingsj** [comment]
ok to test

**Comment by rawlingsj** [comment]
retest this please

**Comment by rawlingsj** [comment]
retest this please

**Comment by rawlingsj** [comment]
ok to test

**Comment by rawlingsj** [comment]
retest this please

**Comment by jstrachan** [comment]
retest this please

**Comment by jstrachan** [comment]
ok to test

**Comment by rawlingsj** [comment]
retest this please

**Pull request closed without merging**
